[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
enunion-helper = { path = "../enunion-helper" }
tokio = { version = "1.38.0", features = ["full"] }
